"""
SHROUD client-side enclave attestation verifier.

This is the trust root for every SHROUD client. Before sending or
receiving a single byte from a relay, the client:

  1. Calls GET /api/v1/attestation on the relay.
  2. Parses the returned COSE_Sign1 document (RFC 9052).
  3. Verifies the signature chains to AWS Nitro Enclaves Root CA
     (https://aws-nitro-enclaves.amazonaws.com/AWS_NitroEnclaves_Root-G1.zip)
  4. Extracts PCR0..PCR8 measurements.
  5. Verifies PCR0 matches the value published in the current SHROUD
     release manifest (signed by the multisig roster — see
     release/multisig.py).
  6. ONLY if all five checks pass, proceeds with the connection.

If verification fails the client SHOULD refuse to talk to the relay.

Wire format of the relay's /api/v1/attestation endpoint:
    GET /api/v1/attestation?nonce=<32_byte_hex>
    -> 200 application/cbor: a COSE_Sign1 CBOR blob
"""
from __future__ import annotations

import base64
import json
import urllib.request
from dataclasses import dataclass
from typing import Optional


# AWS Nitro Enclaves Root CA — pin the SHA-256 of the published bundle.
# Source: https://aws-nitro-enclaves.amazonaws.com/AWS_NitroEnclaves_Root-G1.zip
AWS_NITRO_ROOT_CA_SHA256 = (
    "641a0321a3e244efe456463195d606317ed7cdcc3c1756e09893f3c68f79bb5b"
)


@dataclass
class AttestationVerificationResult:
    ok: bool
    pcr0: Optional[str] = None
    pcr1: Optional[str] = None
    pcr2: Optional[str] = None
    pcr3: Optional[str] = None
    pcr4: Optional[str] = None
    public_key: Optional[bytes] = None
    user_data: Optional[bytes] = None
    nonce: Optional[bytes] = None
    reason: Optional[str] = None


def fetch_and_verify(
    relay_url: str,
    expected_pcr0: str,
    nonce: bytes,
    *,
    timeout: float = 10.0,
) -> AttestationVerificationResult:
    """Fetch the relay's attestation document and verify it end-to-end.

    Args:
        relay_url: base URL of the relay (https://...)
        expected_pcr0: the PCR0 hex string from the signed release manifest
        nonce: a fresh 32-byte random value generated by THIS client
        timeout: HTTP fetch timeout

    Returns:
        AttestationVerificationResult.ok == True iff every check passed.

    Security notes:
        - The nonce MUST be fresh per request — it goes into the attestation
          document so the relay can't replay an old one.
        - expected_pcr0 MUST come from a multisig-verified release manifest,
          not from the relay itself (that would be self-attesting).
        - Cert chain validation MUST verify against the pinned root CA hash
          above. Otherwise an attacker can substitute their own root.
    """
    nonce_hex = nonce.hex()
    url = f"{relay_url.rstrip('/')}/api/v1/attestation?nonce={nonce_hex}"

    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            doc_cbor = resp.read()
    except Exception as e:
        return AttestationVerificationResult(ok=False, reason=f"fetch failed: {e}")

    # Parse COSE_Sign1.
    try:
        from cose.messages import Sign1Message  # type: ignore
        from cose.keys import EC2Key  # type: ignore
        from cose.algorithms import Es384  # noqa: F401
    except ImportError:
        return AttestationVerificationResult(
            ok=False,
            reason="pip install cose; pycose is required to verify Nitro attestations",
        )

    try:
        msg = Sign1Message.decode(doc_cbor)
    except Exception as e:
        return AttestationVerificationResult(ok=False, reason=f"CBOR decode failed: {e}")

    # The payload is a CBOR map with module_id, timestamp, digest, pcrs,
    # certificate, cabundle, public_key, user_data, nonce.
    import cbor2  # type: ignore

    try:
        payload = cbor2.loads(msg.payload)
    except Exception as e:
        return AttestationVerificationResult(ok=False, reason=f"payload decode failed: {e}")

    # ── 1. Verify the leaf certificate chain to the Nitro root ──
    leaf_cert_der = payload.get("certificate")
    cabundle = payload.get("cabundle", [])
    if not leaf_cert_der or not cabundle:
        return AttestationVerificationResult(ok=False, reason="missing cert/cabundle")

    chain_ok = _verify_chain_to_nitro_root(leaf_cert_der, cabundle)
    if not chain_ok:
        return AttestationVerificationResult(
            ok=False, reason="cert chain does not link to pinned Nitro root"
        )

    # ── 2. Verify the COSE_Sign1 signature using the leaf's public key ──
    try:
        from cryptography import x509
        from cryptography.hazmat.backends import default_backend
        leaf = x509.load_der_x509_certificate(leaf_cert_der, default_backend())
        pub = leaf.public_key()
    except Exception as e:
        return AttestationVerificationResult(ok=False, reason=f"leaf cert parse failed: {e}")

    msg.key = _wrap_ec_key_for_cose(pub)
    if not msg.verify_signature():
        return AttestationVerificationResult(ok=False, reason="COSE_Sign1 signature invalid")

    # ── 3. Verify nonce echoed back is the one we sent ──
    returned_nonce = payload.get("nonce")
    if returned_nonce != nonce:
        return AttestationVerificationResult(
            ok=False, reason="nonce mismatch (possible replay)"
        )

    # ── 4. Verify PCR0 matches the published expected value ──
    pcrs = payload.get("pcrs", {})
    pcr0_bytes = pcrs.get(0)
    pcr0_hex = pcr0_bytes.hex() if pcr0_bytes else ""
    if pcr0_hex.lower() != expected_pcr0.lower():
        return AttestationVerificationResult(
            ok=False,
            reason=f"PCR0 mismatch: got {pcr0_hex}, expected {expected_pcr0}",
        )

    return AttestationVerificationResult(
        ok=True,
        pcr0=pcr0_hex,
        pcr1=pcrs.get(1, b"").hex() if pcrs.get(1) else None,
        pcr2=pcrs.get(2, b"").hex() if pcrs.get(2) else None,
        pcr3=pcrs.get(3, b"").hex() if pcrs.get(3) else None,
        pcr4=pcrs.get(4, b"").hex() if pcrs.get(4) else None,
        public_key=payload.get("public_key"),
        user_data=payload.get("user_data"),
        nonce=returned_nonce,
    )


def _verify_chain_to_nitro_root(leaf_der: bytes, cabundle: list[bytes]) -> bool:
    """Walk the cabundle chain and verify it terminates at the pinned root."""
    import hashlib

    from cryptography import x509
    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.exceptions import InvalidSignature

    if not cabundle:
        return False

    root_der = cabundle[-1]
    root_sha256 = hashlib.sha256(root_der).hexdigest()
    if root_sha256.lower() != AWS_NITRO_ROOT_CA_SHA256.lower():
        return False

    # Build the chain: leaf -> intermediates (reverse order) -> root
    chain = [x509.load_der_x509_certificate(leaf_der, default_backend())]
    for der in cabundle:
        chain.append(x509.load_der_x509_certificate(der, default_backend()))

    # Verify each cert is signed by the next one in the chain.
    for i in range(len(chain) - 1):
        child, parent = chain[i], chain[i + 1]
        parent_pub = parent.public_key()
        try:
            if isinstance(parent_pub, ec.EllipticCurvePublicKey):
                parent_pub.verify(
                    child.signature,
                    child.tbs_certificate_bytes,
                    ec.ECDSA(child.signature_hash_algorithm),
                )
            else:
                return False
        except InvalidSignature:
            return False

    return True


def _wrap_ec_key_for_cose(pub):
    """Wrap a cryptography EC public key into a cose EC2Key for verification."""
    from cose.keys import EC2Key
    from cose.algorithms import Es384
    from cose.curves import P384
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurvePublicKey

    if not isinstance(pub, EllipticCurvePublicKey):
        raise ValueError("Nitro leaf must be EC")

    numbers = pub.public_numbers()
    x = numbers.x.to_bytes(48, "big")
    y = numbers.y.to_bytes(48, "big")
    k = EC2Key(crv=P384, x=x, y=y, optional_params={"ALG": Es384})
    return k


# ── Reference usage ──────────────────────────────────────────────────

if __name__ == "__main__":
    import secrets
    import sys

    if len(sys.argv) < 3:
        print(
            "usage: attestation_verifier.py <relay_url> <expected_pcr0_hex>",
            file=sys.stderr,
        )
        sys.exit(2)

    relay_url = sys.argv[1]
    expected_pcr0 = sys.argv[2]
    nonce = secrets.token_bytes(32)

    result = fetch_and_verify(relay_url, expected_pcr0, nonce)
    print(json.dumps({
        "ok": result.ok,
        "pcr0": result.pcr0,
        "reason": result.reason,
    }, indent=2))
    sys.exit(0 if result.ok else 1)
