# SHROUD ProGuard Rules
-keep class com.shroud.client.** { *; }
-keepclassmembers class com.shroud.client.** { *; }
-dontwarn javax.crypto.**
-dontwarn java.security.**
-dontwarn com.google.errorprone.annotations.**
-dontwarn com.google.api.client.**
-dontwarn javax.annotation.**
-dontwarn javax.annotation.concurrent.**
-dontwarn org.joda.time.**
-keep class com.google.crypto.tink.** { *; }
-keep class androidx.security.crypto.** { *; }
