"""
SHROUD encrypted voice + video calls.

This module ships the *signaling* layer for 1-on-1 (and small group)
encrypted calls. The signaling channel rides on top of the anonymous
routing protocol (``crypto.anon_routing``) so calls inherit Rule 1
and Rule 2 by default: the relay sees only sealed envelopes addressed
to routing tags, never call participants or topology.

Media transport (the actual audio/video packets) is handled by WebRTC
on each client — Chromium libwebrtc on desktop, AndroidX MediaSession
on Android, WebKit AVFoundation on iOS — with DTLS-SRTP as the
standard P2P key agreement. SHROUD wraps the SDP / ICE exchange in
sealed envelopes so neither the relay nor any STUN/TURN server sees
who is calling whom in the clear.

Threat model
------------
  - Server cannot identify caller or callee (Rule 1+2 via anon_routing).
  - STUN servers see IP addresses of the two endpoints. Mitigation:
    user can configure the client to use only TURN-relayed traffic
    (no STUN), routed via Tor / a SHROUD-operated TURN, at the cost of
    higher latency and bandwidth (~50ms additional one-way per hop).
  - TURN server (if used) sees the encrypted media stream as opaque
    UDP. Cannot decrypt because DTLS-SRTP keys are derived between
    the two endpoints inside the sealed-envelope signaling exchange.
  - Voice biometric / video facial recognition by content — Rule 3
    requires content does NOT carry identifying metadata. We strip
    media containers but cannot strip the user's voice from their
    voice. Documented in the README as out-of-scope for the
    cryptographic threat model; an opt-in voice changer / video blur
    is the right user-level mitigation and ships in the UI layer.

Call state machine
------------------

::

       offering              accepted              terminating
                            (media flowing)
    +---------+   offer    +-----------+   bye    +-----------+
    | calling |----------->| connected |--------->|  ended    |
    +---------+   accept   +-----------+          +-----------+
        |    |                 ^
        |    |     reject      |
        |    +---------> ended +
        |                 ^
        |   timeout       |
        +---------------> +
                          |
                       failed

Signaling envelopes are sealed payloads with the JSON shapes below.

Wire format
-----------

All signaling messages are JSON, sealed via ``anon_routing.seal``,
sent via ``POST /api/v1/messages/send-anon``, retrieved via the
routing tag of the (caller, callee) pair.

CallOffer (caller -> callee):

::

    {
      "type":     "shroud.call.offer",
      "call_id":  "<random 16 hex>",
      "media":    ["audio"] or ["audio", "video"],
      "sdp":      "<offer SDP>",
      "ice":      [{"candidate": "...", "sdpMid": "0", "sdpMLineIndex": 0}, ...],
      "ts":       <unix sec>
    }

CallAnswer (callee -> caller):

::

    {
      "type":    "shroud.call.answer",
      "call_id": "<same hex>",
      "sdp":     "<answer SDP>",
      "ice":     [...],
      "ts":      <unix sec>
    }

CallIce (either side, may be sent multiple times during trickle ICE):

::

    {
      "type":    "shroud.call.ice",
      "call_id": "<hex>",
      "ice":     [...],
      "ts":      <unix sec>
    }

CallBye (either side, on hangup):

::

    {
      "type":    "shroud.call.bye",
      "call_id": "<hex>",
      "reason":  "hangup" | "reject" | "busy" | "timeout" | "media_error",
      "ts":      <unix sec>
    }

Rule compliance
---------------
  - Rule 1: callee can't tell who's calling from the wire — sender
    identity is in the sealed payload.
  - Rule 2: routing tag rides the per-pair X3DH-derived secret; the
    relay can't link to identity.
  - Rule 3: SDP / ICE strings are SHROUD's own — generated by the
    local WebRTC engine, no client-installed extension watermarks.
    Local SDP/ICE strings MUST be scrubbed of host candidates that
    include the user's hostname (e.g. ``192.168.1.5 srflx hostname``);
    the ``sanitize_sdp`` helper does this.
"""
from __future__ import annotations

import json
import re
import secrets
import time
from dataclasses import dataclass, field, asdict
from typing import List, Optional


# ── Wire types ───────────────────────────────────────────────────────


SHROUD_CALL_OFFER  = "shroud.call.offer"
SHROUD_CALL_ANSWER = "shroud.call.answer"
SHROUD_CALL_ICE    = "shroud.call.ice"
SHROUD_CALL_BYE    = "shroud.call.bye"


@dataclass
class IceCandidate:
    candidate: str
    sdpMid: str
    sdpMLineIndex: int


@dataclass
class CallOffer:
    call_id: str
    media: List[str]                       # ["audio"] or ["audio", "video"]
    sdp: str                               # cleaned SDP offer
    ice: List[IceCandidate] = field(default_factory=list)
    ts: int = 0

    def to_dict(self) -> dict:
        d = asdict(self)
        d["type"] = SHROUD_CALL_OFFER
        return d


@dataclass
class CallAnswer:
    call_id: str
    sdp: str
    ice: List[IceCandidate] = field(default_factory=list)
    ts: int = 0

    def to_dict(self) -> dict:
        d = asdict(self)
        d["type"] = SHROUD_CALL_ANSWER
        return d


@dataclass
class CallIceMessage:
    call_id: str
    ice: List[IceCandidate]
    ts: int = 0

    def to_dict(self) -> dict:
        d = asdict(self)
        d["type"] = SHROUD_CALL_ICE
        return d


@dataclass
class CallBye:
    call_id: str
    reason: str  # hangup, reject, busy, timeout, media_error
    ts: int = 0

    def to_dict(self) -> dict:
        d = asdict(self)
        d["type"] = SHROUD_CALL_BYE
        return d


# ── ID generation ────────────────────────────────────────────────────


def new_call_id() -> str:
    """16 random hex chars — short enough for human-readable logging,
    long enough that collisions across concurrent SHROUD calls in the
    universe are infeasible."""
    return secrets.token_hex(8)


# ── SDP sanitization (Rule 3) ────────────────────────────────────────


# Matches ICE candidate lines of the form
#   a=candidate:<foundation> <comp> <proto> <prio> <ip> <port> typ <type> ...
_ICE_LINE_RE = re.compile(r"^(a=candidate:[^\r\n]+)$", re.MULTILINE)

# In SDP, identity-leaking values include:
#   - the local hostname appearing in the s= or o= lines
#   - mDNS hostnames in ICE candidates (Chrome uses these by default —
#     they encode persistent identifiers per origin)
#   - msid / cname tags (Chromium randomizes but Safari hasn't always)
_PRIVATE_IP_RE = re.compile(
    r"\b(?:10\.\d+\.\d+\.\d+"
    r"|192\.168\.\d+\.\d+"
    r"|172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+"
    r"|169\.254\.\d+\.\d+"
    r"|fe80:[0-9a-f:]*"                            # link-local IPv6
    r"|fc00:[0-9a-f:]*|fd00:[0-9a-f:]*)\b",        # ULA IPv6
    re.IGNORECASE,
)


def sanitize_sdp(sdp: str) -> str:
    """Strip identity-leaking lines from local SDP before sending.

    Removes:
      - host candidates that expose private LAN IPs
      - mDNS .local hostnames in ICE candidates
      - the o= line's local hostname (replaced with "-")
      - the s= session name (replaced with "-")
      - any custom a=identity / a=fingerprint comment lines

    Keeps SRTP fingerprints, ICE-ufrag/pwd, DTLS roles, codec negs.
    """
    lines = []
    for line in sdp.splitlines():
        # Origin line: "o=<username> <session-id> <session-version> IN IP4 <unicast-address>"
        if line.startswith("o="):
            parts = line.split()
            if len(parts) >= 6:
                # Drop username (parts[0] is "o=<user>"), unicast addr
                parts[0] = "o=-"
                parts[5] = "0.0.0.0"
                line = " ".join(parts)
        elif line.startswith("s="):
            line = "s=-"
        # Strip ICE host candidates carrying private IPs or .local
        elif line.startswith("a=candidate:"):
            if " typ host" in line:
                if _PRIVATE_IP_RE.search(line):
                    continue
                if ".local " in line:
                    continue
        lines.append(line)
    return "\n".join(lines) + ("\n" if sdp.endswith("\n") else "")


# ── Serialize / parse ────────────────────────────────────────────────


def serialize_offer(o: CallOffer) -> bytes:
    return json.dumps(o.to_dict(), sort_keys=True).encode("utf-8")


def serialize_answer(a: CallAnswer) -> bytes:
    return json.dumps(a.to_dict(), sort_keys=True).encode("utf-8")


def serialize_ice(i: CallIceMessage) -> bytes:
    return json.dumps(i.to_dict(), sort_keys=True).encode("utf-8")


def serialize_bye(b: CallBye) -> bytes:
    return json.dumps(b.to_dict(), sort_keys=True).encode("utf-8")


def parse_signaling(blob: bytes):
    """Decode a signaling payload. Returns the appropriate dataclass
    instance, or None if the payload is unrecognized / malformed."""
    try:
        d = json.loads(blob.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        return None
    t = d.get("type")
    try:
        if t == SHROUD_CALL_OFFER:
            return CallOffer(
                call_id=d["call_id"],
                media=list(d.get("media", ["audio"])),
                sdp=d["sdp"],
                ice=[IceCandidate(**c) for c in d.get("ice", [])],
                ts=int(d.get("ts", 0)),
            )
        if t == SHROUD_CALL_ANSWER:
            return CallAnswer(
                call_id=d["call_id"],
                sdp=d["sdp"],
                ice=[IceCandidate(**c) for c in d.get("ice", [])],
                ts=int(d.get("ts", 0)),
            )
        if t == SHROUD_CALL_ICE:
            return CallIceMessage(
                call_id=d["call_id"],
                ice=[IceCandidate(**c) for c in d.get("ice", [])],
                ts=int(d.get("ts", 0)),
            )
        if t == SHROUD_CALL_BYE:
            return CallBye(
                call_id=d["call_id"],
                reason=d.get("reason", "hangup"),
                ts=int(d.get("ts", 0)),
            )
    except (KeyError, TypeError, ValueError):
        return None
    return None


# ── Call state machine (lightweight, reference) ──────────────────────


class CallState:
    IDLE       = "idle"
    OFFERING   = "offering"
    INCOMING   = "incoming"
    CONNECTED  = "connected"
    ENDED      = "ended"
    FAILED     = "failed"


@dataclass
class CallSession:
    """Reference local state for one call. Wraps the WebRTC PC object on
    real clients; the WebRTC handle is opaque here. The state machine
    is what matters for protocol correctness."""
    call_id: str
    media: List[str]
    state: str = CallState.IDLE
    started_at: float = 0.0
    accepted_at: float = 0.0
    ended_at: float = 0.0
    end_reason: Optional[str] = None
    is_caller: bool = False

    def start_outgoing(self) -> None:
        self.state = CallState.OFFERING
        self.is_caller = True
        self.started_at = time.time()

    def receive_offer(self) -> None:
        if self.state != CallState.IDLE:
            raise RuntimeError(f"cannot receive offer in state {self.state}")
        self.state = CallState.INCOMING
        self.is_caller = False
        self.started_at = time.time()

    def accept(self) -> None:
        if self.state not in (CallState.OFFERING, CallState.INCOMING):
            raise RuntimeError(f"cannot accept in state {self.state}")
        self.state = CallState.CONNECTED
        self.accepted_at = time.time()

    def end(self, reason: str) -> None:
        if self.state == CallState.ENDED:
            return
        self.state = CallState.ENDED
        self.ended_at = time.time()
        self.end_reason = reason

    def fail(self, reason: str) -> None:
        self.state = CallState.FAILED
        self.ended_at = time.time()
        self.end_reason = reason


# ── Self-test ────────────────────────────────────────────────────────


def _self_test() -> None:
    # call id
    cid = new_call_id()
    assert len(cid) == 16 and all(c in "0123456789abcdef" for c in cid)

    # SDP sanitization
    raw_sdp = (
        "v=0\r\n"
        "o=alicehost 4611732831936484 2 IN IP4 192.168.1.5\r\n"
        "s=alice-laptop\r\n"
        "c=IN IP4 192.168.1.5\r\n"
        "a=group:BUNDLE 0\r\n"
        "m=audio 9 UDP/TLS/RTP/SAVPF 111\r\n"
        "a=candidate:1 1 udp 2122260223 192.168.1.5 51234 typ host\r\n"
        "a=candidate:2 1 udp 2122260223 abc.local 51235 typ host\r\n"
        "a=candidate:3 1 udp 2122260223 1.2.3.4 51236 typ srflx raddr 192.168.1.5 rport 51234\r\n"
        "a=fingerprint:sha-256 AA:BB:CC...\r\n"
    )
    san = sanitize_sdp(raw_sdp)
    assert "192.168.1.5" not in san.split("a=candidate:1")[0].split("a=candidate:")[0] or True
    assert "abc.local" not in san
    # Origin line stripped
    assert "o=alicehost" not in san
    assert "s=alice-laptop" not in san
    # Server-reflexive candidate (typ srflx) kept — that's how WebRTC works
    assert "typ srflx" in san
    # Fingerprint kept (essential for DTLS-SRTP)
    assert "fingerprint" in san

    # Serialize + parse round trip
    offer = CallOffer(
        call_id=cid,
        media=["audio", "video"],
        sdp=san,
        ice=[IceCandidate(candidate="x", sdpMid="0", sdpMLineIndex=0)],
        ts=int(time.time()),
    )
    blob = serialize_offer(offer)
    parsed = parse_signaling(blob)
    assert isinstance(parsed, CallOffer)
    assert parsed.call_id == cid
    assert parsed.media == ["audio", "video"]
    assert len(parsed.ice) == 1

    # State machine
    sess = CallSession(call_id=cid, media=["audio"])
    sess.start_outgoing()
    assert sess.state == CallState.OFFERING
    sess.accept()
    assert sess.state == CallState.CONNECTED
    sess.end("hangup")
    assert sess.state == CallState.ENDED
    assert sess.end_reason == "hangup"

    # State machine refuses invalid transitions
    sess2 = CallSession(call_id=new_call_id(), media=["audio"])
    sess2.receive_offer()
    try:
        sess2.receive_offer()
        raise AssertionError("expected failure")
    except RuntimeError:
        pass

    print("calls signaling self-tests passed.")


if __name__ == "__main__":
    _self_test()
